/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AudioApp {}
  interface MyComponent {}
  interface PageHome {}
}

declare global {


  interface HTMLAudioAppElement extends Components.AudioApp, HTMLStencilElement {}
  var HTMLAudioAppElement: {
    prototype: HTMLAudioAppElement;
    new (): HTMLAudioAppElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {}
  var HTMLPageHomeElement: {
    prototype: HTMLPageHomeElement;
    new (): HTMLPageHomeElement;
  };
  interface HTMLElementTagNameMap {
    'audio-app': HTMLAudioAppElement;
    'my-component': HTMLMyComponentElement;
    'page-home': HTMLPageHomeElement;
  }
}

declare namespace LocalJSX {
  interface AudioApp {}
  interface MyComponent {}
  interface PageHome {}

  interface IntrinsicElements {
    'audio-app': AudioApp;
    'my-component': MyComponent;
    'page-home': PageHome;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'audio-app': LocalJSX.AudioApp & JSXBase.HTMLAttributes<HTMLAudioAppElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'page-home': LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
    }
  }
}


